### ISSUE TITLE
Deep Link: Higher timecode value #t=1:44:31.203 high CPU load Firefox

### ISSUE THREAD

**Issue by norpol** [podlove/podlove-web-player#235]
Hi, I've just reproduced this issue a several times with a blank Firefox 37.0.1 profile.
If I go to this site http://forschergeist.de/podcast/fg005-wissenschaftskommunikation/#t=1:44:31.203 and the embedded audio-file was not loaded yet, my Firefox CPU load goes really high. I can not reproduce the bug with Vivaldi Preview (fork of Chromium, not tested on Chrom*).
Another bug appears with "Epiphany" (Webkit based browser), where the set time just gets ignored and the player resets the timer back to #t=00:00.

**Comment by line-o** [comment]
Could you please see if you can reproduce the behaviour here 
http://sourcerer.org/examples/cre-206/#t=1:23:45.678

**Comment by norpol** [comment]
Yes, still persists.

**Comment by norpol** [comment]
Fixed? :-)

**Comment by alexander-heimbuch** [comment]
Hey, we migrated v2 and v3 code base to separate repos because they are in maintenance mode. This repo is dedicated to the new v4 player, so this is unfortunately not fixed :/
